version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./etc/nginx:/etc/nginx
    ports:
      - 8080:80
    depends_on:
      - go

  go:
    build:
      dockerfile: ./docker/go/Dockerfile
      context: .
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app/go
    environment:
      POST_ISUCONDITION_TARGET_BASE_URL: localhost
    depends_on: 
      - db
    command: reflex -r '(\.go\z|go\.mod\z)' -s -- sh -c 'go run main.go'

  db:
    image: mariadb:10.3.31
    volumes:
      - ./etc/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
#   command: --default-authentication-plugin=mysql_native_password
